/**
 * doom-display: yamcs-web extension that paints the DOOM frame buffer
 * onto a Canvas and forwards keyboard input as F Prime commands.
 *
 * Loaded through the fprime-yamcs web-extension mechanism:
 *
 *   fprime-yamcs ... --yamcs-web-extension-dirs <this directory>
 *
 * which injects this file as a module script into every yamcs-web page.
 * The extension adds a floating "DOOM" launcher button; clicking it opens
 * a floating panel with the rendered frame stream and keyboard controls.
 * The panel behaves like a window: drag its title bar to move it, drag
 * the bottom-right corner to resize it (the canvas scales with it), and
 * use the title-bar buttons to minimize it to its title bar or close it.
 *
 * Data path: a WebSocket "packets" subscription on the tm_realtime stream
 * delivers every raw downlinked space packet (base64). Packetized
 * telemetry (Svc.TlmPacketizer, APID 4) is decoded directly from the raw
 * bytes: each FrameRowNNN packet carries one Doom.FrameRow struct (one
 * downsampled scanline) and the Palette packet carries the Doom.Palette
 * struct. Raw packets are used instead of parameter subscriptions
 * because a 640-element array parameter encoded as protobuf-JSON is
 * roughly 10x the size of its binary form - at up to 400 rows x 35 Hz
 * that difference matters.
 *
 * The FrameRowNNN/Palette packet ids are resolved at runtime from the
 * YAMCS MDB: the XTCE generated by fprime-to-xtce restricts each packet
 * container on the FPrimePacketId parameter, and containers holding a
 * Doom.FrameRow / Doom.Palette parameter are identified by the type of
 * their first entry. Nothing in this file depends on deployment naming.
 */

// Must match Doom/Doom.fpp: FRAME_WIDTH, FRAME_HEIGHT. These are the
// full-resolution maxima; the FrameDownsampler shrinks both dimensions
// by its DOWNSAMPLE factor and each FrameRow carries its own width, so
// the displayed dimensions are derived per frame.
const MAX_WIDTH = 640;
const MAX_ROWS = 400;

// F Prime packetized-telemetry wire layout (fixed by the framework):
// CCSDS primary header (6) + FwPacketDescriptorType (2) = packet id offset.
// Packet id (2) + time tag (2 base + 1 context + 4 s + 4 us) = data offset.
const SPACE_PACKET_HEADER_LEN = 6;
const PKT_ID_OFFSET = SPACE_PACKET_HEADER_LEN + 2;
const PKT_DATA_OFFSET = PKT_ID_OFFSET + 2 + 2 + 1 + 4 + 4;
const APID_TLM_PKT = 4;

// FrameRow struct layout: frame u32, row u16, width u16, pixels[640].
const ROW_PIXELS_OFFSET = 8;
// Palette struct layout: generation u32, rgb[768].
const PALETTE_RGB_OFFSET = 4;
const PALETTE_BYTES = 768;

// Cap on commands captured per recording; protects browser memory if a
// recording is left running (recording continues while the panel is
// closed).
const MAX_RECORDED_COMMANDS = 10000;

// Browser key -> Doom.DoomKey enum label (Doom.fpp).
const KEY_TO_DOOMKEY = {
    "ArrowUp": "UP", "ArrowDown": "DOWN", "ArrowLeft": "LEFT", "ArrowRight": "RIGHT",
    "w": "UP", "s": "DOWN", "a": "STRAFE_L", "d": "STRAFE_R",
    "Control": "FIRE", " ": "USE", "Enter": "ENTER", "Shift": "SHIFT",
    "Escape": "ESCAPE", "Tab": "TAB", "y": "Y", "n": "N",
    "1": "WEAPON1", "2": "WEAPON2", "3": "WEAPON3", "4": "WEAPON4",
    "5": "WEAPON5", "6": "WEAPON6", "7": "WEAPON7", "p": "PAUSE",
};

class DoomDisplay {
    constructor() {
        this.instance = null;
        this.frameRowPacketIds = new Set();
        this.palettePacketId = null;
        this.commands = {};      // suffix -> qualified name
        this.heldKeys = {};
        this.pixels = new Uint8Array(MAX_WIDTH * MAX_ROWS);
        this.frameWidth = MAX_WIDTH;
        this.frameHeight = MAX_ROWS;
        this.palette = new Uint8Array(PALETTE_BYTES);
        for (let i = 0; i < 256; i++) {  // grayscale ramp until PaletteOut arrives
            this.palette[i * 3] = this.palette[i * 3 + 1] = this.palette[i * 3 + 2] = i;
        }
        this.imageData = null;
        this.frameCount = 0;
        this.rowsReceived = 0;
        this.frameDirty = false;
        this.drawScheduled = false;
        this.websocket = null;
        this.statusText = "connecting...";
        this.statusLine = null;
        // .seq command recorder: while recording, every command sent
        // from this panel is captured with a timestamp; stop-recording
        // downloads them as an F Prime .seq sequence file.
        this.recording = false;
        this.recorded = [];   // {timeMs, qualifiedName, args: {..}}
        this.recordStartMs = 0;
        this.recordTruncated = false;
        // Engine running state: seeded by panel clicks, corrected by
        // the State telemetry channel subscription. Lives on the
        // instance, not the panel DOM, so closing and reopening the
        // panel preserves button labels.
        this.engineStarted = false;
        this.stateParameter = null;
        this.paintEngineButton = null;
        // FPS measurement over a rolling one-second window
        this.fpsWindowStart = performance.now();
        this.fpsWindowFrames = 0;
        this.fps = 0;
    }

    async start() {
        try {
            this.instance = await this.findInstance();
            await this.resolveMdb();
            this.subscribe();
        } catch (err) {
            this.setStatus("error: " + err.message);
            console.error("doom-display:", err);
        }
    }

    setStatus(text) {
        this.statusText = text;
        if (this.statusLine) {
            this.statusLine.textContent = text;
        }
    }

    async fetchJson(url) {
        const response = await fetch(url);
        if (!response.ok) {
            throw new Error(url + " -> HTTP " + response.status);
        }
        return response.json();
    }

    async findInstance() {
        const data = await this.fetchJson("/api/instances");
        const instances = data.instances || [];
        if (instances.length === 0) {
            throw new Error("no YAMCS instances");
        }
        const running = instances.find((i) => i.state === "RUNNING") || instances[0];
        return running.name;
    }

    /**
     * Identify FrameRow/Palette packet containers in the MDB. A container
     * qualifies when it has a packet-id restriction (FPrimePacketId
     * comparison) and a parameter entry named FrameRowNNN or PaletteOut.
     */
    async resolveMdb() {
        let url = "/api/mdb/" + encodeURIComponent(this.instance) + "/containers?limit=500";
        let containers = [];
        for (;;) {
            const page = await this.fetchJson(url);
            containers = containers.concat(page.containers || []);
            if (!page.continuationToken) {
                break;
            }
            url = "/api/mdb/" + encodeURIComponent(this.instance)
                + "/containers?limit=500&next=" + encodeURIComponent(page.continuationToken);
        }
        for (const container of containers) {
            const packetId = this.packetIdRestriction(container);
            if (packetId == null) {
                continue;
            }
            const kind = this.classifyContainer(container);
            if (kind === "frame") {
                this.frameRowPacketIds.add(packetId);
            } else if (kind === "palette") {
                this.palettePacketId = packetId;
            }
        }
        if (this.frameRowPacketIds.size === 0) {
            throw new Error("no FrameRow packet containers in MDB");
        }
        await this.resolveCommands();
    }

    packetIdRestriction(container) {
        for (const comparison of container.restrictionCriteria || []) {
            const parameter = (comparison.parameter || {}).qualifiedName || "";
            if (parameter.endsWith("FPrimePacketId") && comparison.operator === "EQUAL_TO") {
                return Number(comparison.value);
            }
        }
        return null;
    }

    classifyContainer(container) {
        for (const entry of container.entry || []) {
            const name = (entry.parameter || {}).qualifiedName || "";
            if (/FrameRow\d+$/.test(name)) {
                return "frame";
            }
            if (name.endsWith("PaletteOut")) {
                return "palette";
            }
        }
        return null;
    }

    async resolveCommands() {
        // The KeyDown/KeyUp/Start/Stop commands live on the component that
        // emits the frames; search for KeyDown and take its component prefix.
        const data = await this.fetchJson("/api/mdb/" + encodeURIComponent(this.instance)
            + "/commands?q=KeyDown&limit=10");
        const match = (data.commands || []).find((c) => c.qualifiedName.endsWith("KeyDown"));
        if (!match) {
            console.warn("doom-display: no KeyDown command in MDB; input disabled");
            return;
        }
        const prefix = match.qualifiedName.slice(0, -"KeyDown".length);
        for (const suffix of ["KeyDown", "KeyUp", "Start", "Stop", "Reset"]) {
            this.commands[suffix] = prefix + suffix;
        }
        // The State telemetry channel lives on the same component.
        // Verify it exists in the MDB before subscribing; without it
        // the Start/Stop toggle falls back to click-seeded state.
        const stateParameter = prefix + "State";
        try {
            await this.fetchJson("/api/mdb/" + encodeURIComponent(this.instance)
                + "/parameters" + stateParameter.split("/").map(encodeURIComponent).join("/"));
            this.stateParameter = stateParameter;
        } catch (err) {
            console.warn("doom-display: no State parameter in MDB;"
                + " Start/Stop toggle will not track external engine state", err);
        }
    }

    subscribe() {
        const scheme = location.protocol === "https:" ? "wss://" : "ws://";
        const websocket = new WebSocket(scheme + location.host + "/api/websocket");
        this.websocket = websocket;
        websocket.onopen = () => {
            this.setStatus("subscribed");
            websocket.send(JSON.stringify({
                type: "packets",
                id: 1,
                options: {instance: this.instance, stream: "tm_realtime"},
            }));
            if (this.stateParameter) {
                // Track the engine State channel so the Start/Stop
                // toggle follows the real engine state (autoStart, GDS
                // commands, sequences), not just panel clicks.
                websocket.send(JSON.stringify({
                    type: "parameters",
                    id: 2,
                    options: {
                        instance: this.instance,
                        processor: "realtime",
                        id: [{name: this.stateParameter}],
                        sendFromCache: true,
                        abortOnInvalid: false,
                    },
                }));
            }
        };
        websocket.onmessage = (event) => this.onMessage(event);
        websocket.onclose = () => {
            this.setStatus("disconnected - retrying in 2s");
            this.websocket = null;
            setTimeout(() => this.subscribe(), 2000);
        };
    }

    onMessage(event) {
        const message = JSON.parse(event.data);
        if (message.type === "parameters") {
            this.absorbEngineState(message.data);
            return;
        }
        if (message.type !== "packets" || !message.data || !message.data.packet) {
            return;
        }
        const bytes = base64ToBytes(message.data.packet);
        if (bytes.length < PKT_DATA_OFFSET) {
            return;
        }
        const apid = ((bytes[0] & 0x07) << 8) | bytes[1];
        if (apid !== APID_TLM_PKT) {
            return;
        }
        const packetId = (bytes[PKT_ID_OFFSET] << 8) | bytes[PKT_ID_OFFSET + 1];
        if (this.frameRowPacketIds.has(packetId)) {
            this.absorbRow(bytes);
        } else if (packetId === this.palettePacketId) {
            this.absorbPalette(bytes);
        }
    }

    absorbRow(bytes) {
        const view = new DataView(bytes.buffer, bytes.byteOffset + PKT_DATA_OFFSET);
        const frame = view.getUint32(0);
        const row = view.getUint16(4);
        const width = view.getUint16(6);
        if (width < 1 || width > MAX_WIDTH || row >= MAX_ROWS) {
            return;
        }
        // Both dimensions shrink by the same downsample factor, so the
        // frame height follows from the row width.
        const height = Math.round(MAX_ROWS * width / MAX_WIDTH);
        if (width !== this.frameWidth) {
            this.frameWidth = width;
            this.frameHeight = height;
            this.pixels.fill(0);
            this.imageData = null;
        }
        const source = PKT_DATA_OFFSET + ROW_PIXELS_OFFSET;
        if (bytes.length < source + width) {
            return;
        }
        this.pixels.set(bytes.subarray(source, source + width), row * width);
        this.rowsReceived++;
        if (row + 1 >= height) {
            this.frameCount = frame;
            this.frameDirty = true;
            this.fpsWindowFrames++;
            const now = performance.now();
            if (now - this.fpsWindowStart >= 1000) {
                this.fps = this.fpsWindowFrames * 1000 / (now - this.fpsWindowStart);
                this.fpsWindowStart = now;
                this.fpsWindowFrames = 0;
            }
            this.scheduleDraw();
        }
    }

    absorbEngineState(data) {
        for (const pval of (data && data.values) || []) {
            const engValue = pval.engValue || {};
            const state = engValue.stringValue
                || (engValue.enumValue ? engValue.enumValue.label : null);
            if (state == null) {
                continue;
            }
            const running = state === "RUNNING" || state === "STARTING";
            if (running !== this.engineStarted) {
                this.engineStarted = running;
                if (this.paintEngineButton) {
                    this.paintEngineButton();
                }
            }
        }
    }

    absorbPalette(bytes) {
        const source = PKT_DATA_OFFSET + PALETTE_RGB_OFFSET;
        if (bytes.length >= source + PALETTE_BYTES) {
            this.palette.set(bytes.subarray(source, source + PALETTE_BYTES));
        }
    }

    scheduleDraw() {
        // Coalesce draws to the display refresh; frames above the refresh
        // rate overwrite the backbuffer and only the latest is painted.
        if (this.drawScheduled || !this.canvas) {
            return;
        }
        this.drawScheduled = true;
        requestAnimationFrame(() => {
            this.drawScheduled = false;
            this.draw();
        });
    }

    draw() {
        if (!this.canvas || !this.frameDirty) {
            return;
        }
        this.frameDirty = false;
        const ctx = this.canvas.getContext("2d");
        const width = this.frameWidth;
        const height = this.frameHeight;
        if (ctx.canvas.width !== width || ctx.canvas.height !== height) {
            ctx.canvas.width = width;
            ctx.canvas.height = height;
            this.imageData = null;
        }
        if (this.imageData == null) {
            this.imageData = ctx.createImageData(width, height);
            this.imageData.data.fill(0xff);
        }
        const rgba = this.imageData.data;
        const pixels = this.pixels;
        const palette = this.palette;
        for (let i = 0, o = 0; i < width * height; i++, o += 4) {
            const base = pixels[i] * 3;
            rgba[o] = palette[base];
            rgba[o + 1] = palette[base + 1];
            rgba[o + 2] = palette[base + 2];
        }
        ctx.putImageData(this.imageData, 0, 0);
        if (this.statusLine) {
            this.statusLine.textContent = "frame " + this.frameCount
                + " | " + this.fps.toFixed(1) + " fps | rows " + this.rowsReceived
                + " | " + this.statusText;
        }
    }

    sendCommand(suffix, args) {
        const qualifiedName = this.commands[suffix];
        if (!qualifiedName) {
            return;
        }
        // Capture the send time now, but only record the entry once
        // YAMCS accepts the command, so the .seq never contains
        // commands that were not actually issued.
        const entry = this.recording ? {
            timeMs: performance.now() - this.recordStartMs,
            qualifiedName: qualifiedName,
            args: args || {},
        } : null;
        const encodedName = qualifiedName.split("/").map(encodeURIComponent).join("/");
        fetch("/api/processors/" + encodeURIComponent(this.instance) + "/realtime/commands"
            + encodedName, {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify({args: args || {}}),
        }).then((response) => {
            if (!response.ok) {
                console.warn("doom-display: command rejected:", suffix, response.status);
                return;
            }
            if (entry && this.recording) {
                if (this.recorded.length < MAX_RECORDED_COMMANDS) {
                    this.recorded.push(entry);
                } else if (!this.recordTruncated) {
                    this.recordTruncated = true;
                    console.warn("doom-display: recording capped at "
                        + MAX_RECORDED_COMMANDS + " commands; further commands dropped");
                }
            }
        }).catch((err) => console.warn("doom-display: command failed:", suffix, err));
    }

    onKeyDown(event) {
        const key = KEY_TO_DOOMKEY[event.key];
        if (!key) {
            return;
        }
        event.preventDefault();
        if (this.heldKeys[key]) {  // suppress browser autorepeat
            return;
        }
        this.heldKeys[key] = true;
        this.sendCommand("KeyDown", {key: key});
    }

    onKeyUp(event) {
        const key = KEY_TO_DOOMKEY[event.key];
        if (!key) {
            return;
        }
        event.preventDefault();
        this.heldKeys[key] = false;
        this.sendCommand("KeyUp", {key: key});
    }

    releaseHeldKeys() {
        for (const key of Object.keys(this.heldKeys)) {
            if (this.heldKeys[key]) {
                this.heldKeys[key] = false;
                this.sendCommand("KeyUp", {key: key});
            }
        }
    }

    startRecording() {
        this.recording = true;
        this.recorded = [];
        this.recordTruncated = false;
        this.recordStartMs = performance.now();
    }

    stopRecording() {
        this.recording = false;
        this.downloadSeqFile(this.buildSeqFile(this.recorded));
        this.recorded = [];
    }

    /**
     * Render recorded commands as an F Prime .seq file (the format
     * consumed by fprime-seqgen / Svc.CmdSequencer). Each line is
     *   R<HH>:<MM>:<SS>.<mmm> <full.command.mnemonic> <args...>
     * with R-times relative to the previous command. The mnemonic is
     * the YAMCS qualified name minus the root SpaceSystem, joined with
     * dots - the inverse of what fprime-to-xtce does when it nests
     * SpaceSystems from the dotted F Prime dictionary name.
     */
    buildSeqFile(recorded) {
        const lines = [
            "; DOOM command sequence recorded by doom-display on "
                + new Date().toISOString(),
            ";",
        ];
        if (this.recordTruncated) {
            lines.push("; WARNING: recording exceeded " + MAX_RECORDED_COMMANDS
                + " commands; later commands were dropped");
        }
        let previousMs = 0;
        // Entries are appended on POST completion, so slow responses
        // can land out of order; sort by capture time before emitting.
        const ordered = recorded.slice().sort((a, b) => a.timeMs - b.timeMs);
        for (const entry of ordered) {
            const mnemonic = entry.qualifiedName.split("/").filter(Boolean)
                .slice(1).join(".").replace(/\s+/g, "");
            const argText = Object.values(entry.args)
                .map((value) => formatSeqArg(value)).join(" ");
            const deltaMs = Math.max(0, Math.round(entry.timeMs - previousMs));
            previousMs = entry.timeMs;
            lines.push(relativeTimeTag(deltaMs) + " " + mnemonic
                + (argText ? " " + argText : ""));
        }
        return lines.join("\n") + "\n";
    }

    downloadSeqFile(text) {
        const stamp = new Date().toISOString().replace(/[:.]/g, "-");
        const anchor = document.createElement("a");
        const url = URL.createObjectURL(new Blob([text], {type: "text/plain"}));
        anchor.href = url;
        anchor.download = "doom-recording-" + stamp + ".seq";
        document.body.appendChild(anchor);
        anchor.click();
        anchor.remove();
        URL.revokeObjectURL(url);
    }

    buildPanel(onClose) {
        const panel = document.createElement("div");
        panel.style.cssText = "position:fixed;bottom:56px;right:12px;z-index:10000;"
            + "background:#1a1a1a;border:2px solid #770000;border-radius:6px;padding:8px;"
            + "box-shadow:0 4px 24px rgba(0,0,0,0.6);font:12px monospace;color:#ccc;"
            + "display:flex;flex-direction:column;resize:both;overflow:hidden;"
            + "min-width:240px;min-height:32px;max-width:95vw;max-height:95vh;";

        panel.appendChild(this.buildTitleBar(panel, onClose));

        const body = document.createElement("div");
        body.style.cssText = "display:flex;flex-direction:column;flex:1;min-height:0;";
        this.panelBody = body;

        const controls = document.createElement("div");
        controls.style.cssText = "display:flex;gap:6px;align-items:center;margin-bottom:6px;";
        const buttonCss = "background:#333;color:#eee;border:1px solid #555;"
            + "border-radius:3px;padding:2px 10px;cursor:pointer;";

        // Start <-> Stop toggle. Seeded by clicks, corrected by the
        // State telemetry subscription; the label reflects
        // this.engineStarted so it survives close/reopen.
        const startStop = document.createElement("button");
        this.paintEngineButton = () => {
            startStop.textContent = this.engineStarted ? "Stop" : "Start";
        };
        this.paintEngineButton();
        startStop.style.cssText = buttonCss;
        startStop.onclick = () => {
            this.engineStarted = !this.engineStarted;
            this.sendCommand(this.engineStarted ? "Start" : "Stop", {});
            this.paintEngineButton();
        };
        controls.appendChild(startStop);

        const reset = document.createElement("button");
        reset.textContent = "Reset";
        reset.title = "Reset the game back to its initial (title screen) state";
        reset.style.cssText = buttonCss;
        reset.onclick = () => this.sendCommand("Reset", {});
        controls.appendChild(reset);

        // Record <-> Stop Recording toggle; stopping downloads the .seq.
        // Recording continues while the panel is closed; the rebuilt
        // button reflects this.recording.
        const record = document.createElement("button");
        const paintRecord = () => {
            record.textContent = this.recording ? "Stop Recording" : "Record";
            record.style.background = this.recording ? "#770000" : "#333";
        };
        record.title = "Record commands sent from this panel into a .seq sequence file";
        record.style.cssText = buttonCss;
        paintRecord();
        record.onclick = () => {
            if (this.recording) {
                this.stopRecording();
            } else {
                this.startRecording();
            }
            paintRecord();
        };
        controls.appendChild(record);

        const hint = document.createElement("span");
        hint.textContent = "click canvas to focus; WASD/arrows/Space/Ctrl";
        hint.style.color = "#888";
        controls.appendChild(hint);
        body.appendChild(controls);

        const canvas = document.createElement("canvas");
        canvas.width = this.frameWidth;
        canvas.height = this.frameHeight;
        canvas.tabIndex = 0;
        // The canvas backing store stays at the native DOOM resolution;
        // CSS scales it to fill whatever size the panel is resized to,
        // preserving the 16:10 aspect ratio.
        canvas.style.cssText = "display:block;flex:1;min-height:0;width:100%;"
            + "background:#000;outline:none;image-rendering:pixelated;"
            + "object-fit:contain;";
        canvas.onclick = () => canvas.focus();
        canvas.onkeydown = (event) => this.onKeyDown(event);
        canvas.onkeyup = (event) => this.onKeyUp(event);
        canvas.onblur = () => this.releaseHeldKeys();
        body.appendChild(canvas);
        this.canvas = canvas;

        const statusLine = document.createElement("div");
        statusLine.style.cssText = "margin-top:4px;color:#888;flex:none;";
        statusLine.textContent = this.statusText;
        body.appendChild(statusLine);
        this.statusLine = statusLine;

        panel.appendChild(body);
        // Initial size: native canvas plus panel chrome.
        panel.style.width = (MAX_WIDTH + 20) + "px";
        panel.style.height = (MAX_ROWS + 76) + "px";
        return panel;
    }

    buildTitleBar(panel, onClose) {
        const bar = document.createElement("div");
        bar.style.cssText = "display:flex;align-items:center;gap:6px;flex:none;"
            + "margin:-8px -8px 6px -8px;padding:4px 8px;background:#550000;"
            + "color:#fff;cursor:move;user-select:none;touch-action:none;";

        const title = document.createElement("span");
        title.textContent = "DOOM";
        title.style.cssText = "font-weight:bold;flex:1;";
        bar.appendChild(title);

        let minimized = false;
        let restoreHeight = null;
        const minimize = document.createElement("button");
        minimize.textContent = "\u2013";
        minimize.title = "Minimize to title bar";
        const close = document.createElement("button");
        close.textContent = "\u00d7";
        close.title = "Close";
        for (const button of [minimize, close]) {
            button.style.cssText = "background:#772222;color:#fff;border:1px solid #995555;"
                + "border-radius:3px;width:22px;height:18px;line-height:1;cursor:pointer;"
                + "font:bold 12px monospace;padding:0;";
        }
        minimize.onclick = () => {
            minimized = !minimized;
            if (minimized) {
                restoreHeight = panel.style.height;
                this.panelBody.style.display = "none";
                panel.style.resize = "none";
                panel.style.height = "auto";
            } else {
                this.panelBody.style.display = "flex";
                panel.style.resize = "both";
                panel.style.height = restoreHeight;
            }
            minimize.textContent = minimized ? "\u25a1" : "\u2013";
            minimize.title = minimized ? "Restore" : "Minimize to title bar";
        };
        close.onclick = () => onClose();
        bar.appendChild(minimize);
        bar.appendChild(close);

        // Drag-to-move. The panel is created anchored bottom/right; on
        // first drag it is re-anchored top/left so it moves freely.
        bar.addEventListener("pointerdown", (event) => {
            if (event.target !== bar && event.target !== title) {
                return;
            }
            event.preventDefault();
            const rect = panel.getBoundingClientRect();
            panel.style.left = rect.left + "px";
            panel.style.top = rect.top + "px";
            panel.style.right = "auto";
            panel.style.bottom = "auto";
            const offsetX = event.clientX - rect.left;
            const offsetY = event.clientY - rect.top;
            const onMove = (move) => {
                const width = panel.offsetWidth;
                const barHeight = bar.offsetHeight;
                const left = Math.min(Math.max(move.clientX - offsetX, 8 - width),
                                      window.innerWidth - 8);
                const top = Math.min(Math.max(move.clientY - offsetY, 0),
                                     window.innerHeight - barHeight);
                panel.style.left = left + "px";
                panel.style.top = top + "px";
            };
            const onUp = () => {
                window.removeEventListener("pointermove", onMove);
                window.removeEventListener("pointerup", onUp);
            };
            window.addEventListener("pointermove", onMove);
            window.addEventListener("pointerup", onUp);
        });

        return bar;
    }

    install() {
        const launcher = document.createElement("button");
        launcher.textContent = "DOOM";
        launcher.title = "Toggle the DOOM telemetry display";
        launcher.style.cssText = "position:fixed;bottom:12px;right:12px;z-index:10000;"
            + "background:#770000;color:#fff;border:none;border-radius:4px;"
            + "padding:6px 14px;font:bold 13px monospace;cursor:pointer;"
            + "box-shadow:0 2px 8px rgba(0,0,0,0.5);";
        let panel = null;
        const closePanel = () => {
            if (panel != null) {
                panel.remove();
                panel = null;
                this.canvas = null;
                this.statusLine = null;
                this.panelBody = null;
                this.imageData = null;
            }
        };
        launcher.onclick = () => {
            if (panel == null) {
                panel = this.buildPanel(closePanel);
                document.body.appendChild(panel);
                this.frameDirty = true;
                this.draw();
            } else {
                closePanel();
            }
        };
        document.body.appendChild(launcher);
        this.start();
    }
}

function formatSeqArg(value) {
    if (typeof value === "string") {
        // Enum labels (e.g. DoomKey UP) are bare identifiers; anything
        // else is emitted as a quoted string argument with quotes,
        // backslashes, and line breaks sanitized so a recorded value
        // cannot break out of the argument or inject a sequence line.
        if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) {
            return value;
        }
        const sanitized = value.replace(/[\r\n]+/g, " ")
            .replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
        return '"' + sanitized + '"';
    }
    if (typeof value === "boolean") {
        return value ? "TRUE" : "FALSE";
    }
    // Numbers and anything else: strip whitespace so a stray
    // toString cannot split or inject a sequence line.
    return String(value).replace(/\s+/g, "");
}

function relativeTimeTag(deltaMs) {
    const totalSeconds = Math.floor(deltaMs / 1000);
    const hours = Math.floor(totalSeconds / 3600);
    const minutes = Math.floor((totalSeconds % 3600) / 60);
    const seconds = totalSeconds % 60;
    const millis = deltaMs % 1000;
    const pad = (n, w) => String(n).padStart(w, "0");
    return "R" + pad(hours, 2) + ":" + pad(minutes, 2) + ":" + pad(seconds, 2)
        + "." + pad(millis, 3);
}

function base64ToBytes(base64) {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    return bytes;
}

if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", () => new DoomDisplay().install());
} else {
    new DoomDisplay().install();
}
