; ======================================================================
; fprime-stress settings
;
; fprime-stress is a library; downstream deployments are expected to
; reference it via `add_fprime_subdirectory()`. These settings are
; here so the library can be `fprime-util generate`'d in isolation
; for development.
; ======================================================================
[fprime]
framework_path: ../fprime
project_root: .
default_cmake_options: FPRIME_SKIP_TOOLS_VERSION_CHECK=ON
